spring.application.name=agristock

spring.datasource.url=jdbc:mysql://localhost:3306/agristock_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Samsung1*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

server.port=8080

ollama.api.url=http://localhost:11343
ollama.model.name=gpt-oss-120b-cloud